volumes:
  pihole_etc:
  pihole_dnsmasq:

services:
  pihole:
    container_name: pihole
    image: 'pihole/pihole:2025.06.2'
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - 'pihole_etc:/etc/pihole'
      - 'pihole_dnsmasq:/etc/dnsmasq.d'
    ports:
      - '53:53/tcp'
      - '${SERVER_IP}:53:53/udp'
      - '8000:80/tcp'
    environment:
      TZ: Europe/London
      FTLCONF_webserver_api_password: '${PIHOLE_WEB_PASSWORD}'
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: '1.1.1.1'
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_domain: lan
      FTLCONF_dns_reply_host_IPv4: '${SERVER_IP}'
    cap_add:
      - SYS_NICE
      - SYS_TIME
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=home-server_frontend
      - traefik.http.routers.pihole.rule=Host(`pihole.${DNS_SUFFIX}`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
