volumes:
  gluetun:
  qbittorrent_config:

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.40.3
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - '${TORRENT_PORT}:${TORRENT_PORT}/tcp'
      - '${TORRENT_PORT}:${TORRENT_PORT}/udp'
    volumes:
      - gluetun:/gluetun
    networks:
      - frontend
    environment:
      TZ: Europe/London
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${VPN_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${VPN_ADDRESS}
      UPDATER_PERIOD: 24h

  qbittorrent:
    container_name: qbittorrent
    image: qbittorrentofficial/qbittorrent-nox:5.1.4-1
    restart: unless-stopped
    logging:
      options:
        max-size: 10m    
    network_mode: "container:gluetun"
    volumes:
      - 'qbittorrent_config:/config'
      - '${TORRENT_DOWNLOAD_PATH}:/downloads'
    environment:
      TZ: Europe/London
      PUID: ${TORRENT_PUID}
      PGID: ${TORRENT_PGID}
      QBT_LEGAL_NOTICE: confirm
      QBT_VERSION: 5.1.4-1
      QBT_WEBUI_PORT: 8085
    stop_grace_period: 3m
    tmpfs:
      - /tmp
    tty: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=home-server_frontend
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DNS_SUFFIX}`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8085
  
  flood:
    container_name: flood
    image: jesec/flood:4.11.0
    user: '${TORRENT_PUID}:${TORRENT_PGID}'
    command: --port 3001 --allowedpath /downloads
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - '../flood:/config'
      - '${TORRENT_DOWNLOAD_PATH}:/downloads'
    environment:
      TZ: Europe/London
      HOME: /config
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=home-server_frontend
      - traefik.http.routers.flood.rule=Host(`flood.${DNS_SUFFIX}`)
      - traefik.http.routers.flood.entrypoints=web
      - traefik.http.services.flood.loadbalancer.server.port=3001
