volumes:
  homepage_config:

services:
  homepage:
    container_name: homepage
    image: 'ghcr.io/gethomepage/homepage:v1.7.0'
    volumes:
      - 'homepage_config:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=dashboard.${DNS_SUFFIX}
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=home-server_frontend
      - traefik.http.routers.homepage.rule=Host(`dashboard.${DNS_SUFFIX}`)
      - traefik.http.routers.homepage.entrypoints=web
